### ISSUE TITLE
Child Rendering does not ensure raceDef == Human

### ISSUE THREAD

**Issue by pardeike** [thirite/ChildrenAndPregnancy#17]
Seems like an issue with zombies having a CurLifeStageIndex of 1 but I am not sure. I tried different mod loading orders but it does not matter.

**Comment by thirite** [comment]
Yeah, newborns and toddlers skip rendering the head. I suppose I'll need to add checks to ensure the pawn's race is of the Human def when building the graphics to render.

**Comment by thirite** [comment]
Fixed in v0.3j
