### ISSUE TITLE
Please tag stable releases so we can download them even after you move on.

### ISSUE THREAD

**Issue by RafeHaab** [thirite/ChildrenAndPregnancy#18]
I can't download the last stable release because someone forgot to tag it. Would you people please start doing so from now on?

**Comment by Undeadbanana** [comment]
I don't think you should be considering this an "alpha" as it's still in active development. You are basically downloading what's available to help thirite progress toward his goals for an initial alpha release.

Click Code -> Green button on right that says "Clone or Download" -> Download Zip -> Install those files as the mod

**Comment by thirite** [comment]
Currently there is no 'stable' release. Every version up to now has had unresolved bugs.

**Comment by RafeHaab** [comment]
Please close this issue. it was related to me not installing huglibs.
