### ISSUE TITLE
Rewrite breastfeeding mechanics to use unique JobGiver injected into HumanLike thinktree

### ISSUE THREAD

**Issue by thirite** [thirite/ChildrenAndPregnancy#2]

**Comment by thirite** [comment]
Potentially done, just requires testing.

**Comment by thirite** [comment]
Not working due to oversight in how the mechanics function. Needs its own JobGiver entry to be injected into the ThinkTree rather than trying to piggyback the doctoring WorkGiver

**Comment by jacobEAdamson** [comment]
Perhaps a "Mother" labor column? In addition, a baby's eating ability could be set to 0% with the baby Hediff, which would probably disable any of the regular in game patient feeding mechanics (via doctoring).

**Comment by thirite** [comment]
Good idea. I'm working on that now.

**Comment by thirite** [comment]
Fixed in e393ff84e777fbabf49b53722c2dec2d26ee276f
